services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: rsync -a public/ /data/public/ && npm start
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 18.12.1
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: STRIPE_SECRET_KEY
        value: sk_test_51MUPahJTSpQ0bQ3cleWaIplXH7tuhF9Bsv3veHjXMYmc50tFicB9F0cPw5fQbD0YOOgfGIqyj22z5WC1zVWkgY7800Lnkc3wbR
